[package]
name = "v86oxide"
version = "0.1.0"
publish = false

[dependencies]
quickcheck = "0.6.2"

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[profile.dev]
lto = false
panic = "abort"

[profile.release]
lto = true
incremental = false
panic = "abort"

